#!/usr/bin/env python
from modules.installer import Installer

"""[summary]
On-Click installer to power up a new developer's machine into a full K8s local environment.
"""


installer = Installer()
installer.start()
