#!/usr/bin/env python
from src.welcome import Welcome

"""[summary]
On-Click installer to power up a new developer's machine into a full K8s local environment.
"""


Welcome().print_welcome_message()
